# Generated by Django 4.2.6 on 2025-10-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_todotask_created_at_todotask_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
