# Generated by Django 4.2.6 on 2025-10-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_department_employee_remove_employees_department_and_more'),
    ]

    operations = [
    ]
