# Generated by Django 4.2.6 on 2025-10-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0008_category_creator_profile_default_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='creator',
        ),
    ]
