# Generated by Django 4.2.6 on 2025-10-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0010_category_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
